name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Get Google AI API Key from Secret Manager
        id: get-api-key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BARTERVERSE_L9UQ3 }}' > /tmp/service-account.json
          gcloud auth activate-service-account --key-file=/tmp/service-account.json
          API_KEY=$(gcloud secrets versions access latest --secret="google-ai-api-key" --project="barterverse-l9uq3")
          echo "::add-mask::$API_KEY"
          echo "GOOGLE_API_KEY=$API_KEY" >> $GITHUB_ENV
          # Create .env.production for Firebase deployment (the working approach)
          echo "GOOGLE_API_KEY=$API_KEY" > .env.production
          rm /tmp/service-account.json
      
      - name: Build project  
        run: npm run build
        env:
          GOOGLE_API_KEY: ${{ env.GOOGLE_API_KEY }}
          NEXT_PUBLIC_BUILD_COMMIT: ${{ github.sha }}
          NEXT_PUBLIC_BUILD_BRANCH: ${{ github.head_ref }}
          NEXT_PUBLIC_BUILD_TIME: ${{ github.event.head_commit.timestamp || github.run_started_at }}
        
      - name: Deploy to Firebase Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase_deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BARTERVERSE_L9UQ3 }}'
          projectId: barterverse-l9uq3
          target: barterverse-auto-deploy
          expires: 7d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          GOOGLE_API_KEY: ${{ env.GOOGLE_API_KEY }}
      
      - name: Comment on PR with deployment info
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentUrl = '${{ steps.firebase_deploy.outputs.details_url }}' || 'https://barterverse-auto-deploy.web.app';
            const commit = '${{ github.event.pull_request.head.sha }}'.slice(0, 7);
            const branch = '${{ github.head_ref }}';
            const buildTime = new Date().toLocaleString();
            
            const comment = `## 🚀 Preview Deployment Successful!
            
            **🌐 Preview URL:** ${deploymentUrl}  
            **📝 Branch:** \`${branch}\`  
            **💾 Commit:** \`${commit}\`  
            **⏰ Built:** ${buildTime}  
            **🔧 APIs:** Secret Manager integration enabled ✅
            
            **Quick Links:**
            - [📱 Open Preview Site](${deploymentUrl})
            - [🔧 Test API Endpoint](${deploymentUrl}/api/test-key)
            - [📊 View Commit](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }})
            
            *Preview expires in 7 days*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });