name: Universal Pipeline
on:
  repository_dispatch:
    types: [pipeline]
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.ref }}
          path: ./app
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: chmod +x ../auto-detect.sh && ../auto-detect.sh
        working-directory: ./app