name: Universal Pipeline
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          path: ./app
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: chmod +x ./auto-detect.sh && ./auto-detect.sh
        working-directory: ./app